name: discordshell
description: A shell for discord bots
version: 0.1.0-next
homepage: https://github.com/Benny-/discordshell
author: Benny Jacobs <benny@gmx.it>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  json_annotation: ^2.0.0
  markdown: ^2.0.2
  logging: "^0.11.3+2"
  nyxx:
    path: nyxx
    #git:
    #  url: git://github.com/benny-/nyxx.git
    #  ref: development

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.4+2
  json_serializable: ^2.0.0

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc
